version: '3.8'

services:
  beacond:
    build:
      context: .
      dockerfile: Dockerfile.beacond
    volumes:
      - beacond_data:/app/var/beacond
      - logs:/app/logs
      - seed_data:/app/seed-data-80069
    ports:
      - "26657:26657"  # RPC port
      - "26656:26656"  # P2P port
    networks:
      - beranet

  reth:
    build:
      context: .
      dockerfile: Dockerfile.reth
    volumes:
      - reth_data:/app/var/reth
      - logs:/app/logs
      - seed_data:/app/seed-data-80069
      - beacond_data:/app/var/beacond:ro  # Read-only access to JWT
    ports:
      - "8545:8545"    # HTTP RPC port
      - "30303:30303"  # P2P port
    networks:
      - beranet

volumes:
  beacond_data:
  reth_data:
  logs:
  seed_data:

networks:
  beranet: