version: '3.8'

services:
  beacond:
    build:
      context: .
      dockerfile: Dockerfile.beacond
    volumes:
      - berachain_data:/app/var
      - berachain_logs:/app/logs
      - berachain_seed:/app/seed-data-80069
    ports:
      - "26657:26657"  # RPC
      - "26656:26656"  # P2P
    networks:
      - berachain-net
    restart: unless-stopped

  reth:
    build:
      context: .
      dockerfile: Dockerfile.reth
    volumes:
      - berachain_data:/app/var
      - berachain_logs:/app/logs
      - berachain_seed:/app/seed-data-80069
    ports:
      - "9656:8545"    # RPC
      - "8551:8551"    # Auth
      - "30303:30303"  # P2P
    depends_on:
      - beacond
    networks:
      - berachain-net
    restart: unless-stopped

volumes:
  berachain_data:
  berachain_logs:
  berachain_seed:

networks:
  berachain-net:
    driver: bridge