services:
  beacond:
    build:
      context: .
      dockerfile: beacond/Dockerfile
    platform: linux/amd64
    environment:
      CHAIN_SPEC: ${CHAIN_SPEC}
      CHAIN_ID: ${CHAIN_ID}
      MONIKER_NAME: "docker-node"
      WALLET_ADDRESS_FEE_RECIPIENT: "0x9BcaA41DC32627776b1A4D714Eef627E640b3EF5"
      EL_ARCHIVE_NODE: "false"
      JWT_PATH: "/app/shared/jwt.hex"
    volumes:
      - beacond-data:/app/var/beacond
      - shared:/app/shared
      - seed-data:/app/seed-data-${CHAIN_ID}
    ports:
      #- "32000:32000" # CL_ETHRPC_PORT
      - "32001:32001" # CL_ETHP2P_PORT

  reth:
    build:
      context: .
      dockerfile: reth/Dockerfile
    platform: linux/amd64
    environment:
      CHAIN_SPEC: ${CHAIN_SPEC}
      CHAIN_ID: ${CHAIN_ID}
      EL_ARCHIVE_NODE: "false"
      JWT_PATH: "/app/shared/jwt.hex"
    volumes:
      - reth-data:/app/var/reth
      - shared:/app/shared
      - seed-data:/app/seed-data-${CHAIN_ID}
    ports:
      - "32003:32003"     # EL_ETHRPC_PORT (PORT_BASE 32000)
      - "32005:32005"     # EL_ETH_PORT (PORT_BASE 32000)
      - "32005:32005/udp" # EL_ETH_PORT (PORT_BASE 32000)
    depends_on:
      - beacond

volumes:
  seed-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/seed-data-${CHAIN_ID}

  beacond-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/beacond
  
  reth-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/reth

  shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared