version: '3.8'

services:
  beacond:
    build: ./beacond
    platform: linux/arm64
    environment:
      CHAIN_SPEC: testnet
      MONIKER_NAME: "docker-node"
      WALLET_ADDRESS_FEE_RECIPIENT: "0x9BcaA41DC32627776b1A4D714Eef627E640b3EF5"
      EL_ARCHIVE_NODE: "false"
      JWT_PATH: "/app/shared/jwt.hex"
    volumes:
      - beacond-data:/app/var/beacond
      - shared:/app/shared
    ports:
      - "26657:26657"   # CL RPC
      - "26656:26656"   # CL P2P

  reth:
    build: ./reth
    platform: linux/arm64
    environment:
      CHAIN_SPEC: testnet
      EL_ARCHIVE_NODE: "false"
      JWT_PATH: "/app/shared/jwt.hex"
    volumes:
      - reth-data:/app/var/reth
      - shared:/app/shared
    ports:
      - "8545:8545"     # EL RPC
      - "30303:30303"   # EL P2P
    depends_on:
      - beacond

volumes:
  beacond-data:
  reth-data:
  shared: